server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    # serverTimezone=GMT%2B8 东八区，领先全球标准时间UTC八个小时
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.chenbo.daomybatis

# showSql
logging:
  level:
    com:
      example:
        mapper : debug
