server:
  port: 8080

spring:
  datasource:

    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    driver-class-name: org.postgresql.Driver
    url: jdbc:p6spy:postgresql://192.168.0.100:5432/test
    username: test
    password: test

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

mybatis-plus:
  typeEnumsPackage: com.chenbo.daomybatisplus.auth.enums