server:
  port: 9999
  # 配置静态资源启用 gzip 压缩
  compression:
    enabled: true
    min-response-size: 128
# 配置主数据源
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost/magic-api?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
#  data:
    # 配置mongo数据源
#    mongodb:
#      host: localhost
#      port: 27017
#      database: magicapi
#      username: magicapi
#      password: 123456
  # 配置redis数据源
#  redis:
#    host: localhost
#    port: 6379
#    database: 4
#    timeout: 5000
magic-api:
  web: /magic/web
  resource:
    #配置文件存储位置。当以classpath开头时，为只读模式
    #mac用户请改为可读写的目录
    #如果不想存到文件中，可以参考配置将接口信息存到数据库、Redis中（或自定义）
#    location: D:/magic-api
    location: classpath:magic-api
#    type: database  # 配置接口存储方式，这里选择存在数据库中
#    table-name: magic_api_file_v2  # 数据库中的表名
#    prefix: /magic-api  # 前缀
# 其它配置请参考 https://ssssssss.org/magic-api/config/
