server:
  port: 8080

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.151:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted


knife4j:
  enable: true
  openapi:
    title: Knife4j文档
    description: "单体项目最佳实践"
    email: chenboprogrammer@gmail.com
    concat: 无根水
    url: https://github.com/wugenshui
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 默认
        api-rule: package
        api-rule-resources:
          - com.github.wugenshui.best.practice.single.controller
  setting:
    enable-host: true
    enable-host-text: http://localhost:8080
