server:
  port: 8080

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.0.151:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted

knife4j:
  enable: true
  setting:
    enable-host: true
    enable-host-text: http://localhost:${server.port}
