server:
  port: 8080

spring:
  datasource:

    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    # serverTimezone=GMT%2B8 Asia/Shanghai 东八区，领先全球标准时间UTC八个小时
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: root

#    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:p6spy:oracle:thin:@192.168.0.204:1521:helowin
    username: simp
    password: abcd-1234

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:p6spy:postgresql://192.168.0.100:5432/test
#    username: test
#    password: test

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.chenbo.daomybatis

# showSql
#logging:
#  level:
#    root: warn
#    com.chenbo.daomybatisplus.auth.mapper: trace
#  pattern:
#    console: '%p%m%n'
