spring:
  cloud:
    gateway:
      # 网关配置文档：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html
      routes:
        # 唯一id
        - id: oauth
          # 真实请求地址，lb是loadbalancer负载均衡的缩写，oauth是注册服务名
          uri: lb://oauth
          # 断言：满足条件时才会代理
          predicates:
            # 当请求路径以/oauth/开头时
            - Path=/oauth/**
          filters:
            # 附加至代理请求
            - AddRequestHeader=X-Request-Foo, Bar
            - AddRequestParameter=foo, bar
            # 附加至响应
            - AddResponseHeader=X-Response-Foo, Bar
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
        - id: test
          uri: http://localhost:8080
          predicates:
            - Path=/test/**
          filters:
            - RewritePath=/test/(?<segment>.*), /user/$\{segment}
        # 权重，流量分流，数值越高，比例越高
        - id: weight_high
          uri: https://www.baidu.com
          predicates:
            - Weight=group1, 2
            - Path=/weight
          filters:
            # 去除自己添加的一层前缀:/weight
            - StripPrefix=1
        - id: weight_low
          uri: https://www.hao123.com
          predicates:
            - Weight=group1, 1
            - Path=/weight
          filters:
            - StripPrefix=1
