spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

export:
  ignore-tables: "ABNORMAL_INFORM,FUNCTIONS,JOB,JOB_ROLE,JOB_USER,LOGS,OAUTH_ACCESS_TOKEN,OAUTH_APPROVALS,OAUTH_CLIENT_DETAILS,OAUTH_CLIENT_TOKEN,OAUTH_CODE,OAUTH_REFRESH_TOKEN,OU,OU_JOB,OU_ROLE,OU_USER,ROLES,ROLE_DATA,ROLE_FUNCTION,USER_ROLE"
  db-template: classpath:template/hw-db.docx
  table-template: classpath:template/mysql-table.docx