server:
  port: 8080

spring:
  redis:
    host: 192.168.0.204
    port: 6379
    password: 1q2w#E$R
    database: 2
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  cache:
    redis:
      # Entry expiration in milliseconds. By default the entries never expire.
      time-to-live: 1d
      # 写入redis时是否使用键前缀
      use-key-prefix: true

# showSql
logging:
  level:
    com:
      chenbo:
        demo:
          redis:
            cache:
              mapper: debug
