server:
  port: 8080

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    # serverTimezone=GMT%2B8 Asia/Shanghai 东八区，领先全球标准时间UTC八个小时
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://192.168.0.217:5236?schema=TEST
    username: SYSDBA
    password: SYSDBA001

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mybatis.plus.mysql.sims.entity
