server:
  port: 8080

spring:
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  #type-aliases-package: com.chenbo.daomybatis

# showSql
logging:
  level:
    root: warn
    com.chenbo.daomybatisplus.auth.mapper: trace
  pattern:
    console: '%p%m%n'
